// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe9mp3loH9JVh7uxF6B8W7ihbxs7q_dsI',
    appId: '1:102736654530:web:bd15a9a1fdb33ae89f4b5b',
    messagingSenderId: '102736654530',
    projectId: 'chat-application-f0936',
    authDomain: 'chat-application-f0936.firebaseapp.com',
    storageBucket: 'chat-application-f0936.firebasestorage.app',
    measurementId: 'G-WGTL0G54K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbiRtCuP4Zv293PaEC3y7U1s8pXrzJLjI',
    appId: '1:102736654530:android:e78fd6f977751e329f4b5b',
    messagingSenderId: '102736654530',
    projectId: 'chat-application-f0936',
    storageBucket: 'chat-application-f0936.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHeskvj-ZszQ08HNUwD3XmPvlZRYPNPJM',
    appId: '1:102736654530:ios:583f63a147b1b1c99f4b5b',
    messagingSenderId: '102736654530',
    projectId: 'chat-application-f0936',
    storageBucket: 'chat-application-f0936.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );
}
